// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpzZln_05LdfqWVN8Nz5WndhIuSN11UC8',
    appId: '1:179737203058:web:f90f2edb9d7f04eea28deb',
    messagingSenderId: '179737203058',
    projectId: 'pos-system-app-a3249',
    authDomain: 'pos-system-app-a3249.firebaseapp.com',
    storageBucket: 'pos-system-app-a3249.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVZS1dnA6C1Et2GNlNSpUP9sGzoGQYc-U',
    appId: '1:179737203058:android:f5216c6f89d2e594a28deb',
    messagingSenderId: '179737203058',
    projectId: 'pos-system-app-a3249',
    storageBucket: 'pos-system-app-a3249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvDdbdNW-MKTtYBAISYK-sPmN_uARWuWQ',
    appId: '1:179737203058:ios:02d14ed92b740a45a28deb',
    messagingSenderId: '179737203058',
    projectId: 'pos-system-app-a3249',
    storageBucket: 'pos-system-app-a3249.firebasestorage.app',
    iosBundleId: 'com.example.posSystemApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvDdbdNW-MKTtYBAISYK-sPmN_uARWuWQ',
    appId: '1:179737203058:ios:02d14ed92b740a45a28deb',
    messagingSenderId: '179737203058',
    projectId: 'pos-system-app-a3249',
    storageBucket: 'pos-system-app-a3249.firebasestorage.app',
    iosBundleId: 'com.example.posSystemApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpzZln_05LdfqWVN8Nz5WndhIuSN11UC8',
    appId: '1:179737203058:web:0be4a25d3009d0bea28deb',
    messagingSenderId: '179737203058',
    projectId: 'pos-system-app-a3249',
    authDomain: 'pos-system-app-a3249.firebaseapp.com',
    storageBucket: 'pos-system-app-a3249.firebasestorage.app',
  );
}
